name: Run Tests

on:
  push:
    branches: [ master, staging ]
  pull_request_target:
    branches: [ master, staging ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.TEST_POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Enable Corepack
      run: corepack enable

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'yarn'
  
    - name: Install dependencies
      run: yarn install

    - name: Generate Prisma Client
      run: yarn db:generate

    - name: Run Database Migrations
      run: yarn db:migrate:production
      env:
        DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Javascript REPL image
      uses: docker/build-push-action@v6
      with:
        context: src/base_images/javascript
        load: true
        no-cache: true
        push: false
        tags: js-base:latest

    - name: Build Python REPL image
      uses: docker/build-push-action@v6
      with:
        context: src/base_images/python
        load: true
        no-cache: true
        push: false
        tags: py-base:latest

    - name: Run tests with coverage
      run: yarn test
      env:
        NODE_ENV: test
        DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        WHITELIST: ${{ secrets.TEST_WHITELIST }}
        SECRET: ${{ secrets.TEST_SECRET }}